### ISSUE TITLE
Missing stdlib.h: No file directory

### ISSUE THREAD

**Issue by grumpyman12601** [FyraLabs/submarine#7]
**SKID ALERT**

# About the issues

I have been trying to install Submarine, but after installing all of the dependencies, I get the error while installing u-root, is this a u-root issue or a Submarine issue? My apologies if it isn't for this repository. 

## Error

chronos@sasuke-rev5 ~ $ go install github.com/u-root/u-root@latest

runtime/cgo
_cgo_export.c:3:10: fatal error: stdlib.h: No such file or directory
    3 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.

## Possible Issues
I get the error if I'm running it on xfce4-terminal, or VT-2. When searching for a mention of it, nothing comes up when searching for stdlib.h in FyraLabs, elfutils, or u-root.  

It could be elfutils-devel, or openssl-devel, and I know there are issues here because I have not installed the developer versions of these. 

Another issue could be that I am installing these using Chromebrew, installing the apps onto my chromebook with the prebuilt apps in the crew database.
I'm not sure if I need to install stuff using Crostini and the terminal there.

Info: Samsung Chromebook Go, v120, x64_x86, Intel Celeron processor.

Any help would be appreciated, I know a lot of the issues I have will affect the installation, but I'm trying to bug patch my installation early on so I know the issues.

**Comment by ellyq** [comment]
You shouldn't be compiling it in ChromeOS. You might be able to get headers from chromebrew, but... why?

**Comment by nothingneko** [comment]
Hi, you can download a prebuilt image from the link in the readme. Instructions can be found here: https://wiki.ultramarine-linux.org/en/anywhere/chromebook/#manual-installation---not-recommended

**Comment by grumpyman12601** [comment]
> You shouldn't be compiling it in ChromeOS. You might be able to get glibc headers from chromebrew, but... why?

I haven't seen a lot of stuff on this topic and misunderstood the instructions, but chromebrew had most avalable packages besides u-root and the devel branches of the programs.

I will continue to try to install this, but my system files alone are at 21.6 GB so I'll have to recover my ChromeOS.

**Comment by grumpyman12601** [comment]
> Hi, you can download a prebuilt image from the link in the readme. Instructions can be found here: https://wiki.ultramarine-linux.org/en/anywhere/chromebook/#manual-installation---not-recommended

I never found this originally, I'll use it as a reference, thank you!
