### ISSUE TITLE
Touchscreen support

### ISSUE THREAD

**Issue by Pegoku** [FyraLabs/submarine#8]
I would like to know if it is possible to use the touchscreen with this bootloader. With eupnea, you could use it, do i need to add a driver/DKMS?
PS: i have the chrultrabook Kernel.

**Comment by WeirdTreeThing** [comment]
This has nothing to do with whether your touchscreen works once you boot the actual linux distro.

**Comment by ellyq** [comment]
Ditto, bootloader gets removed from memory and replaced with Linux kernel.

Touchscreen on x86 pretty much requires custom Coreboot build due to power sequencing.

**Comment by WeirdTreeThing** [comment]
No, you just need to reload modules in a funny order.

**Comment by Pegoku** [comment]
> No, you just need to reload modules in a funny order.

On what order? how do i do it?
